name: FastBuild
main: io.github.yodalee.FastBuild.FastBuild
version: 1.10.2
description: fast build allow you to break/build at most 64 blocks on one click.
author: yodalee
commands:
  setn:
    description: set number n
    usage: "Usage: /setn number"
    permission: FastBuild.setn
    permission-message: You don't have <permission>
  setnh:
    description: TODO
    usage: "Usage: /seth number"
    permission: FastBuild.setn
    permission-message: You don't have <permission>
  setnv:
    description: TODO
    usage: "Usage: /setn number"
    permission: FastBuild.setn
    permission-message: You don't have <permission>
  togglePlaceMode:
    description: toggle place mode(use in hand/in inventory)
    usage: "Usage: /togglePlaceMode"
    permission: FastBuild.togglePlaceMode
    permission-message: You don't have <permission>
permissions:
  FastBuild.*:
    description: Gives access to all fastbuild commands
    children:
      FastBuild.setn: true
  FastBuild.setn:
    description: Allows you to set n
    default: true
  FastBuild.togglePlaceMode:
    description: Allows you to toggle place mode
    default: true
